export { default as Hero } from './Hero';
export { default as Services } from './Services';
export { default as Projects } from './Projects';
export { default as Process } from './Process';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as Testimonials } from './Testimonials';
export { default as Team } from './Team';
export { default as Contact } from './Contact';
export { default as Pricing } from './Pricing';
